"""empty message

Revision ID: 371ffd7fce2c
Revises: 45405ee75e48
Create Date: 2018-08-06 23:47:00.964727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371ffd7fce2c'
down_revision = '45405ee75e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_lookup', sa.Column('expiration_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card_lookup', 'expiration_date')
    # ### end Alembic commands ###
