"""empty message

Revision ID: 722fd3415dca
Revises: 05ebeaa64398
Create Date: 2018-08-13 21:19:34.655247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '722fd3415dca'
down_revision = '05ebeaa64398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image_file', sa.TEXT(), nullable=True))
    op.drop_column('card', 'image_link_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image_link_url', mysql.TEXT(), nullable=True))
    op.drop_column('card', 'image_file')
    # ### end Alembic commands ###
