"""empty message

Revision ID: 7927ff412d37
Revises: da1eb0020e98
Create Date: 2018-09-03 11:45:02.991282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7927ff412d37'
down_revision = 'da1eb0020e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preference', sa.Column('from_date', sa.DATETIME(), nullable=True))
    op.add_column('user_preference', sa.Column('to_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preference', 'to_date')
    op.drop_column('user_preference', 'from_date')
    # ### end Alembic commands ###
