"""empty message

Revision ID: 825440647b46
Revises: 11401b7b3d55
Create Date: 2018-08-07 22:51:49.482540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '825440647b46'
down_revision = '11401b7b3d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
