"""empty message

Revision ID: a07f76b045c5
Revises: 722fd3415dca
Create Date: 2018-08-14 20:32:30.915872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07f76b045c5'
down_revision = '722fd3415dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_lookup', sa.Column('status', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card_lookup', 'status')
    # ### end Alembic commands ###
