"""empty message

Revision ID: c8cb8db4e1ed
Revises: 825440647b46
Create Date: 2018-08-07 22:56:01.515899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8cb8db4e1ed'
down_revision = '825440647b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signup_bonus', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.drop_column('signup_bonus', 'status')
    op.add_column('user_card_lookup', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.drop_column('user_card_lookup', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_lookup', sa.Column('status', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('user_card_lookup', 'active')
    op.add_column('signup_bonus', sa.Column('status', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column('signup_bonus', 'active')
    # ### end Alembic commands ###
