"""empty message

Revision ID: da1eb0020e98
Revises: e9408150e617
Create Date: 2018-09-03 11:42:46.849430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1eb0020e98'
down_revision = 'e9408150e617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preference', sa.Column('active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preference', 'active')
    # ### end Alembic commands ###
