"""empty message

Revision ID: e9408150e617
Revises: f2d5dd7c1f84
Create Date: 2018-09-03 11:21:06.830625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9408150e617'
down_revision = 'f2d5dd7c1f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preference', sa.Column('reward_company_1', sa.VARCHAR(length=50), nullable=True))
    op.add_column('user_preference', sa.Column('reward_company_2', sa.VARCHAR(length=50), nullable=True))
    op.add_column('user_preference', sa.Column('reward_company_3', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('user_preference', 'reward_copmany_2')
    op.drop_column('user_preference', 'reward_copmany_1')
    op.drop_column('user_preference', 'reward_copmany_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preference', sa.Column('reward_copmany_3', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('user_preference', sa.Column('reward_copmany_1', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('user_preference', sa.Column('reward_copmany_2', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('user_preference', 'reward_company_3')
    op.drop_column('user_preference', 'reward_company_2')
    op.drop_column('user_preference', 'reward_company_1')
    # ### end Alembic commands ###
