"""empty message

Revision ID: f175bc08d9c1
Revises: 484ee256924c
Create Date: 2018-07-07 08:05:38.644280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f175bc08d9c1'
down_revision = '484ee256924c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward', sa.Column('annual_fee_waived', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reward', 'annual_fee_waived')
    # ### end Alembic commands ###
