"""empty message

Revision ID: f2d5dd7c1f84
Revises: e23da2ef95d6
Create Date: 2018-09-03 11:19:56.066373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d5dd7c1f84'
down_revision = 'e23da2ef95d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('own_company', sa.BOOLEAN(), nullable=True),
    sa.Column('reward_category_1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reward_copmany_1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reward_category_2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reward_copmany_2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reward_category_3', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reward_copmany_3', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    # ### end Alembic commands ###
