"""empty message

Revision ID: fc8f05548fec
Revises: fabfbc1e580f
Create Date: 2018-07-07 07:46:33.364848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8f05548fec'
down_revision = 'fabfbc1e580f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_reward_lookup_ibfk_1', 'user_reward_lookup', type_='foreignkey')
    op.create_foreign_key(None, 'user_reward_lookup', 'reward', ['reward_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_reward_lookup', type_='foreignkey')
    op.create_foreign_key('user_reward_lookup_ibfk_1', 'user_reward_lookup', 'card', ['reward_id'], ['id'])
    # ### end Alembic commands ###
